version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8.3.0 x64
  - npm install npm@latest -g
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run build
  - yarn run test-e2e
  - yarn run release

test: off
