// flow-typed signature: 36e2cf427f61ba2126f1d29b9975e9e2
// flow-typed version: <<STUB>>/boiler-room-custodian_v^0.6.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boiler-room-custodian'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boiler-room-custodian' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boiler-room-custodian/app/modules/config' {
  declare module.exports: any;
}

declare module 'boiler-room-custodian/app/modules/file-ops' {
  declare module.exports: any;
}

declare module 'boiler-room-custodian/app/mop' {
  declare module.exports: any;
}

declare module 'boiler-room-custodian/test/mop-tests' {
  declare module.exports: any;
}

declare module 'boiler-room-custodian/test/repo/setup' {
  declare module.exports: any;
}

declare module 'boiler-room-custodian/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boiler-room-custodian/app/modules/config.js' {
  declare module.exports: $Exports<'boiler-room-custodian/app/modules/config'>;
}
declare module 'boiler-room-custodian/app/modules/file-ops.js' {
  declare module.exports: $Exports<'boiler-room-custodian/app/modules/file-ops'>;
}
declare module 'boiler-room-custodian/app/mop.js' {
  declare module.exports: $Exports<'boiler-room-custodian/app/mop'>;
}
declare module 'boiler-room-custodian/test/mop-tests.js' {
  declare module.exports: $Exports<'boiler-room-custodian/test/mop-tests'>;
}
declare module 'boiler-room-custodian/test/repo/setup.js' {
  declare module.exports: $Exports<'boiler-room-custodian/test/repo/setup'>;
}
declare module 'boiler-room-custodian/test/util.js' {
  declare module.exports: $Exports<'boiler-room-custodian/test/util'>;
}
