// flow-typed signature: 6f2e06ed18c94a6e11966da31c0170de
// flow-typed version: <<STUB>>/electron-builder-squirrel-windows_v^19.36.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-builder-squirrel-windows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-builder-squirrel-windows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-builder-squirrel-windows/out/squirrelPack' {
  declare module.exports: any;
}

declare module 'electron-builder-squirrel-windows/out/squirrelWindows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-builder-squirrel-windows/out/squirrelPack.js' {
  declare module.exports: $Exports<'electron-builder-squirrel-windows/out/squirrelPack'>;
}
declare module 'electron-builder-squirrel-windows/out/squirrelWindows.js' {
  declare module.exports: $Exports<'electron-builder-squirrel-windows/out/squirrelWindows'>;
}
