// flow-typed signature: 46c5031e5648f89339928d09560b034f
// flow-typed version: <<STUB>>/keytar-prebuild_v^4.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keytar-prebuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keytar-prebuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keytar-prebuild/lib/keytar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keytar-prebuild/lib/keytar.js' {
  declare module.exports: $Exports<'keytar-prebuild/lib/keytar'>;
}
