export const SETTINGS_LOAD_ERROR = 'SETTINGS_LOAD_ERROR';
export const SETTINGS_PARSE_ERROR = 'SETTINGS_PARSE_ERROR';
export const ERROR_ALERT = 'ERROR_ALERT';
export const INFO_ALERT = 'INFO_ALERT';
